# Generated by Django 4.2.7 on 2023-11-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='especializacion',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
