# Generated by Django 4.2.7 on 2023-11-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_doctor_especializacion_paciente_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='especializacion',
        ),
        migrations.AddField(
            model_name='doctor',
            name='especialización',
            field=models.CharField(default='Médico General', max_length=50),
        ),
    ]
