# Generated by Django 4.2.7 on 2023-11-26 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_rename_especialización_doctor_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medico.doctor'),
        ),
    ]
