# Generated by Django 4.2.7 on 2023-11-26 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0005_paciente_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='doctor',
        ),
    ]
