# Generated by Django 4.2.7 on 2023-11-26 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0006_remove_cita_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='doctor',
        ),
        migrations.AddField(
            model_name='cita',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medico.doctor'),
        ),
    ]
