# Generated by Django 4.2.7 on 2023-11-26 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0007_remove_paciente_doctor_cita_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='paciente',
        ),
        migrations.AddField(
            model_name='doctor',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medico.paciente'),
        ),
    ]
