# Generated by Django 4.2.7 on 2023-11-26 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0009_cita_doctor_cita_paciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='historial',
            new_name='motivo',
        ),
    ]
