# Generated by Django 4.2.7 on 2023-11-26 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0010_rename_historial_paciente_motivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='paciente',
        ),
        migrations.AddField(
            model_name='paciente',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='medico.doctor'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='medico.doctor'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='medico.paciente'),
        ),
    ]
