# Generated by Django 4.2.7 on 2023-11-26 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0011_remove_doctor_paciente_paciente_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctor',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medico.paciente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medico.doctor'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medico.paciente'),
        ),
    ]
